#------------------------------------------------------------------
#------------------------------------------------------------------
#------------------------------------------------------------------
#------------------------------------------------------------------

#Warning01:Unpacking the tuple,and konwing 
# the tuple is immutable

#Warning1.5:In dict Using Key as element to store value
#Setting[Key]=Value,if not Key in Setting,it would create a new one


#Warning1.75:
    # 1. Remove a specific dict or tuple using remove():

        # my_list = [
        #     {"name": "Alice", "age": 30},
        #     (1, 2, 3),
        #     99
        # ]

        # my_dict = {"name": "Alice", "age": 30}
        # my_tuple = (1, 2, 3)

        # my_list.remove(my_dict)   # remove dictionary
        # my_list.remove(my_tuple)  # remove tuple

        # print(my_list)

    # 2. Remove by index using del:
        # del my_list[0]   # delete the first element
        # del my_list[1]   # delete the element at index 1


#Warning02:Use list as a store method

#Warning03:Use join to concatenate the charecter and string

#Warning04:Capitilize the first letter of each name
    #settings={...}
    #for key in settings:
       #key.capitalize()

#------------------------------------------------------------------








